[package]
name = "zk_coinbase_attestation"
type = "bin"
authors = ["LuchoLeonel", "fabian416"]

[dependencies]
eddsa = { tag = "v0.1.1", git = "https://github.com/noir-lang/eddsa" }
ecrecover = { tag = "v0.30.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
