[package]
name = "zk_coinbase_attestation"
type = "bin"
authors = ["LuchoLeonel", "fabian416"]

[dependencies]
ecrecover = { tag = "v0.30.0", git = "https://github.com/colinnielsen/ecrecover-noir" }
keccak256 = { tag = "v0.1.0", git = "https://github.com/noir-lang/keccak256" }
